language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
  - travis_retry composer self-update

before_script:
  - composer install --no-interaction --prefer-dist --no-suggest
  - php console key:generate
  - chmod -R 777 storage/
  - chmod -R 777 public/upload/
  - chmod -R 777 public/cache/

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v
  - travis_retry bash <(curl -s https://codecov.io/bash)
