<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `console optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    */

    'files' => [

    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled File Providers
    |--------------------------------------------------------------------------
    |
    | Here you may list service providers which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    |
    */

    'providers' => [

    ],

    /*
     |----------------------------------------------------------------------------
     | Compiled Files
     |----------------------------------------------------------------------------
     |
     | Here you can list the file location which holds the list classes that needs
     | to be compiled.
     */
    'locations' => [
        '{path.vendor}speedwork/framework/compiles.txt',
    ],
];
